### ISSUE TITLE
 Django baton Reverse for 'app_list' with keyword arguments '{'app_label': 'auth'}' not found

### ISSUE THREAD

**Issue by linhnvhicts** [otto-torino/django-baton#124]
Hello, when i try to add baton to my project, the following error came up on console when i go into the index page. The sidebar of app not rendering at all
previous template i used was jazzmin and it worked normal, this came up after i replaced it with baton
My settings.py:

```
INSTALLED_APPS = [
    'backend.apps.BackendConfig',
    'api.apps.ApiConfig',
    'settings.apps.SettingsConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'rest_framework',
    'timezone_field',
    'social_django',
    'drf_yasg',
    'corsheaders',
    'baton',
    'django.contrib.admin',
    'baton.autodiscover'
]

# Baton config
BATON = {
    'SITE_HEADER': 'Test Admin',
    'SITE_TITLE': 'test admin',
    'INDEX_TITLE': 'TEST ADMIN',
    'SUPPORT_HREF': '',
    'CONFIRM_UNSAVED_CHANGES': True,
    'SHOW_MULTIPART_UPLOADING': True,
    'ENABLE_IMAGES_PREVIEW': True,
    'MENU': (
        {
            'type': 'app',
            'name': 'backend',
            'label': 'test_sidebar',
            'models': (
                {
                    'name': 'assignment',
                    'label': 'Assignment'
                }
            )
        }
    ),
}

```

I also made a custom admin_site to override some base admin url and add my custom views in admin.py:

```
from django.urls import include, path
from django.template.response import TemplateResponse
from backend.models import *
from django.shortcuts import render, redirect
from django.urls import reverse
from .forms import *
from django.contrib.auth import authenticate, login
from django.contrib import messages
from baton.autodiscover import admin


#https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_urls
class CustomAdminSite(admin.AdminSite):
  
    def get_urls(self):
        urls = super(CustomAdminSite, self).get_urls()
        custom_urls = [
            path('student-profile/', self.student_profile ,name="student_profile"),
            path('signup/', self.signup ,name="signup"),
        ]
        return urls + custom_urls
    
    def student_profile(self, request):
        if request.method == 'GET':
            user = request.user
            user_courses = StudentCourseStatus.objects.filter(student=user)
            context = dict(
            # Include common variables for rendering the admin template.
            self.each_context(request),
            # Anything else you want in the context...
            courses=user_courses
            )
            return TemplateResponse(request, "student_profile.html", context)
    
    def signup(self, request):
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                email = form.cleaned_data.get('email')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, email=email, password=raw_password)
                messages.success(request, 'Register Succesful, please login again')
        else:
            form = RegisterForm()

        if request.user.is_authenticated:
            return redirect(reverse('admin:index'))
        else:
            context = dict(
                # Include common variables for rendering the admin template.
                self.each_context(request),
                # Anything else you want in the context...
                form=form
            )
            return TemplateResponse(request, 'admin/signup.html', context)                    

admin_site = CustomAdminSite()
```

And lastly my urls.py:

```
from .admin import admin_site

admin_site.site_header = os.environ.get(
    'admin_site_HEADER') or 'Django administration'

urlpatterns = [
    path('api/', include('api.urls')),
    path('', admin_site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('baton/', include('baton.urls')),
    path('graphql', GraphQLView.as_view(graphiql=True)),
    path('swagger-ui/', TemplateView.as_view(
        template_name='swagger-ui.html',
        extra_context={'schema_url': 'openapi-schema'}
    ), name='swagger-ui'),
    path('openapi/', get_schema_view(
        title="Your Project",
        description="API for all things …",
        version="1.0.0"
    ), name='openapi-schema'),
]

if settings.DEBUG or 'test' in sys.argv:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
```

here is the full error trace back:
```
Traceback (most recent call last):
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/baton/views.py", line 18, in dispatch
    return super(GetAppListJsonView, self).dispatch(*args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/baton/views.py", line 26, in get
    self.app_list = site.get_app_list(request)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 485, in get_app_list
    app_dict = self._build_app_dict(request)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 467, in _build_app_dict
    'app_url': reverse(
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'app_list' with keyword arguments '{'app_label': 'auth'}' not found. 1 pattern(s) tried: ['(?P<app_label>backend|settings)/$']
[19/Dec/2020 04:06:50] "GET /baton/app-list-json/ HTTP/1.1" 500 115651
[19/Dec/2020 04:06:53] "GET /settings/language/add/ HTTP/1.1" 200 12761
[19/Dec/2020 04:06:53] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[19/Dec/2020 04:06:53] "GET /static/admin/css/forms.css HTTP/1.1" 200 12
[19/Dec/2020 04:06:53] "GET /jsi18n/ HTTP/1.1" 200 3187
[19/Dec/2020 04:06:53] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[19/Dec/2020 04:06:53] "GET /baton/gravatar/ HTTP/1.1" 200 44
Internal Server Error: /baton/app-list-json/
Traceback (most recent call last):
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/baton/views.py", line 18, in dispatch
    return super(GetAppListJsonView, self).dispatch(*args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/baton/views.py", line 26, in get
    self.app_list = site.get_app_list(request)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 485, in get_app_list
    app_dict = self._build_app_dict(request)
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 467, in _build_app_dict
    'app_url': reverse(
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'app_list' with keyword arguments '{'app_label': 'auth'}' not found. 1 pattern(s) tried: ['(?P<app_label>backend|settings)/$']
```
I can't seem to find where this error come from, i know it's related to the baton sidebar because it's not rendering on index place. Does my custom adminsite correct for baton?

this is what happened on the page 
<img width="1262" alt="Screen Shot 2020-12-19 at 2 06 34 PM" src="https://user-images.githubusercontent.com/46511495/102683428-86de9000-4203-11eb-9736-76ea8f0f13c8.png">

**Comment by linhnvhicts** [comment]
i tried removing my custom AdminSite and went with the default urls.py like in the readme and the sidebar is rendering again?
Can you tell me how can i customize baton AdminSite so i can override login and add signup view?

Django docs provide way to override admin view like so https://docs.djangoproject.com/en/3.1/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_urls but it doesn't work with baton sidebar

**Comment by abidibo** [comment]
Hi @linhnvhicts , 

I'm not sure I've spot the whole problem here. But, if you want to override the `AdminSite` class you can do this way (tested and working):

Create and `admin.py` in your main app (let's call it `app`). Here you define your `CustomAdminSite` which inherits from `BatonAdminSite`

``` python
# file app/admin.py
from baton.autodiscover import admin
from django.urls import include, path
from django.template.response import TemplateResponse

class CustomAdminSite(admin.BatonAdminSite):
    def get_urls(self):
        urls = super(CustomAdminSite, self).get_urls()
        custom_urls = [
            path('profile/',
                 self.profile,
                 name="profile"),
            path('signup/', self.signup, name="signup"),
        ]
        return urls + custom_urls

    def profile(self, request):
        return TemplateResponse(request, "admin/profile.html", {})

    def signup(self, request):
        return TemplateResponse(request, 'admin/signup.html', {})


admin_site = CustomAdminSite()
```

Then, in your `urls.py` you should add this new `admin_site`:

``` python
# file app/urls.py
# from baton.autodiscover import admin
from django.urls import path, include, re_path
from .admin import admin_site #`this is your custom admin_site

urlpatterns = [
    path('admin/', admin_site.urls),
    path('baton/', include('baton.urls')),
]
```

And finally make sure the application of your admin_siote appears as the last one in `INSTALLED_APPS` (it should take the place of `baton.autodiscover`):

``` python
# file app/settings.py
INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ... my other apps
    'app',  # this is the main app which define the admin.py
]
```

Let me know if it works for you, thanks!

**Comment by linhnvhicts** [comment]
@abidibo thank you! the problem was the apps should be in the end of INSTALLED_APPS

```
INSTALLED_APPS = [
    'baton',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'rest_framework',
    'timezone_field',
    'social_django',
    'drf_yasg',
    'corsheaders',
    'backend.apps.BackendConfig', #add 3 of my apps to the end and replace baton.autodiscover
    'api.apps.ApiConfig',
    'settings.apps.SettingsConfig',
]
```

Would be nice if this also included in your documents if people want to override AdminSite 😄

**Comment by linhnvhicts** [comment]
oh...a problem, the sidebar rendered but none of the apps i listed in the menu showing

![Uploading Screen Shot 2020-12-19 at 7.39.13 PM.png…]()

**Comment by abidibo** [comment]
Difficult to say why without debugging. In the network panel of chrome, what do you see for the app_list request? Also your overall settings are different from my tests. I'm available for a debug session with TeamViewer if you want, just leave me your contacts to abidibo@gmail.com, we can have a call later.

**Comment by linhnvhicts** [comment]
@abidibo thank for the response i sent you an email with my teamviewer informations,  i checked network tab and app-list-json returning empty list

**Comment by abidibo** [comment]
Anyway, I'd try this:

virtualenv/baton/views.py, line 28, add:

    import pdb;pdb.set_trace()

Run the app, and return to the terminal

    (pdb) self.app_list

You should see a list of dictionaries representing all the apps. If you see an empty list, then it means that `site.app_list(request)` is returning an empty list. Such list is checked when showing voices, because only apps land models listed here can be shown for permissions reasons. If this is the case check what is site:

    (pdb) site

You should see something like 

    <django.contrib.admin.sites.DefaultAdminSite object at 0x7f51cfdd9160>

We can start from here

**Comment by linhnvhicts** [comment]
sorry i can't share the repo clone as it's my school project, but i appreciate the help 😃
