### ISSUE TITLE
problem with select2

### ISSUE THREAD

**Issue by etanter** [otto-torino/django-baton#82]
Hi,
Not sure if this is directly related to baton or not. But it might, and if not, maybe you have an idea of what's going wrong here...

I'm using `django-select2` together with `baton`, in order to provide nice choice/related widgets. 
Whenever possible with Django admin (2.2) I use the `autocomplete_fields` feature, but this only works for fields that are foreign keys, not for choices, so for these ones I just use the "by hand" select2, ie:
```
class CustomModelForm(ModelForm):
    class Meta:
        widgets = {
            'category': Select2Widget(attrs={'width': ...}),  
            ...
```
when the corresponding page is loaded, however, I get this JS error trace in the Chrome console:
```
jquery.js:4055 Uncaught TypeError: $element.select2 is not a function
    at init (django_select2.js:14)
    at HTMLSelectElement.<anonymous> (django_select2.js:58)
    at Function.each (jquery.js:381)
    at _.fn.init.$.fn.djangoSelect2 (django_select2.js:53)
    at HTMLDocument.<anonymous> (django_select2.js:71)
    at l (jquery.js:3762)
    at s (jquery.js:3830)
```
prior to this, there's a "deferred exception" that puts baton in the stack trace:
```
jquery.js:4046 jQuery.Deferred exception: $element.select2 is not a function TypeError: $element.select2 is not a function
    at init (http://127.0.0.1:8000/dev/admin/static/django_select2/django_select2.js:14:14)
    at HTMLSelectElement.<anonymous> (http://127.0.0.1:8000/dev/admin/static/django_select2/django_select2.js:58:9)
    at Function.each (http://127.0.0.1:8000/dev/admin/static/baton/app/dist/baton.min.js:14:2946)
    at _.fn.init.$.fn.djangoSelect2 (http://127.0.0.1:8000/dev/admin/static/django_select2/django_select2.js:53:7)
    at HTMLDocument.<anonymous> (http://127.0.0.1:8000/dev/admin/static/django_select2/django_select2.js:71:26)
    at l (http://127.0.0.1:8000/dev/admin/static/baton/app/dist/baton.min.js:25:26162)
    at s (http://127.0.0.1:8000/dev/admin/static/baton/app/dist/baton.min.js:25:26464) undefined
```
In the console I see first the deferred exception, then Baton:init, then Baton:ready, then the actual TypeError.

Any idea what's going on? 
Thanks!

**Comment by abidibo** [comment]
Hi @etanter ,
it has something to do with the fact that baton also includes jquery in its bundle, and the order in which baton and other js resources are defined. The problem disappears if you invert the order, for example change a bit the `admin/base_site.html`:

(notice the `blockbots` instead of `extrahead`)

```
{% block blockbots %}{{ block.super }}
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <script src="{% static 'baton/app/dist/baton.min.js' %}"></script>
    <!-- <script src="http://localhost:8080/dist/baton.min.js"></script> -->
    <script>
        {% baton_config 'CONFIRM_UNSAVED_CHANGES' as confirm_unsaved_changes %}
        {% baton_config 'SHOW_MULTIPART_UPLOADING' as show_multipart_uploading %}
        {% baton_config 'ENABLE_IMAGES_PREVIEW' as enable_images_preview %}
        {% baton_config 'CHANGELIST_FILTERS_IN_MODAL' as changelist_filters_in_modal %}
        {% baton_config 'MENU_ALWAYS_COLLAPSED' as menu_always_collapsed %}
        {% baton_config 'MENU_TITLE' as menu_title %}
        (function ($, undefined) {
            $(window).on('load', function () {
                Baton.init({
                    api: {
                        app_list: '{% url 'baton-app-list-json' %}'
                    },
                    confirmUnsavedChanges: {{ confirm_unsaved_changes|yesno:"true,false" }},
                    showMultipartUploading: {{ show_multipart_uploading|yesno:"true,false" }},
                    enableImagesPreview: {{ enable_images_preview|yesno:"true,false" }},
                    changelistFiltersInModal: {{ changelist_filters_in_modal|yesno:"true,false" }},
                    menuAlwaysCollapsed: {{ menu_always_collapsed|yesno:"true,false" }},
                    menuTitle: '{{ menu_title|escapejs }}'
                });
            })
        })(jQuery, undefined)
    </script>
{% endblock %}
```

I'm using jquery in baton only for browser support. It's still quite a nightmare to deal with all different old browser versions when manipulating the DOM. So at the moment I think I won't be able to fix this.

**Comment by etanter** [comment]
Thanks @abidibo - I think this patch via `base_site.html` is good enough for me. I understand that it's likely not something you want to address per se in baton.
